### ISSUE TITLE
Thank you for this extension

### ISSUE THREAD

**Issue by ahrjarrett** [victorteokw/recenter-top-bottom#10]
Hello Victor!

Please close this issue when you see it.

Usually I wouldn't open an issue for something like this, but I needed to say thank you. I've spent a few years now missing this feature from Emacs, and was finally so frustrated that I started investigating how to implement this myself.

Then I did what I should have done a long time ago, and Googled "recenter-top-bottom vscode", and when I saw how closely this extension approximates the behavior from Emacs, I literally shouted.

Thank you.

**Comment by victorteokw** [comment]
Hi @ahrjarrett Thanks!
