### ISSUE TITLE
Avoid needing to install inside remote

### ISSUE THREAD

**Issue by david-morris** [victorteokw/recenter-top-bottom#11]
This is a purely editor-based extension. It doesn't seem to use the remote side of a remote connection.

Therefore, it would be convenient to change the packaging details so that that's how it installs. Then it wouldn't need to be installed in every remote you use.

I've fixed a bug with a similar cause before: https://github.com/sansarip/owlbear/issues/114 .

I'm using user settings to force running the extension as ui-only and will update on its functionality.

**Comment by victorteokw** [comment]
Hi @david-morris, thanks. How to merge the pr?

**Comment by david-morris** [comment]
I'll try to get around to putting a PR together this weekend.

Hmm, I just noticed this is an older extension.  Hopefully this won't need any updates to the package.json formatting.

If all goes well it should just be a version bump and adding `extensionKinds: ["ui"]` in the [package.json](https://github.com/sansarip/owlbear/pull/115/files).

**Comment by victorteokw** [comment]
Thanks @david-morris

**Comment by david-morris** [comment]
I've just confirmed that adding `"yeannylam.recenter-top-bottom": ["ui"]` under `remote.extensionKind` in user settings solves the problem for the user.  That means that if the same fix in package.json works, that should solve this ticket.

**Comment by victorteokw** [comment]
Hi @david-morris , could you provide the PR and I'll merge right after seeing the PR

**Comment by victorteokw** [comment]
Hi @david-morris, the new version is published, thanks!
